In [381]:
import pandas as pd
import os

In [382]:
segSummaries =  "A:/1 - TDM/3 - Model Dev/1 - WF/1 - Official Release/v9x/v9.0/WF TDM v9.0 - official/Scenarios/_roadwaysegsummaries"
scnJson = "_site/data/scnData/scenarios.json"

In [383]:

data = [
    {
        "attributes": [
            {
                "aCode" : "aDist",
                "aName" : "Distance",
            },
            {
                "aCode" : "aLanes",
                "aName" : "Lanes",
            },
            {
                "aCode" : "aFt",
                "aName" : "Functional Type",
            },
            {
                "aCode" : "aFtClass",
                "aName" : "Function Group"
            },
            {
                "aCode" : "aCap1HL",
                "aName" : "Capacity per Hour per Lane"
            },
            {
                "aCode" : "aCap1HL",
                "aName" : "Capacity per Hour per Lane"
            },
            {
                "aCode" : "aFfSpd",
                "aName" : "Free-flow Speed"
            },
            {
                "aCode" : "aVol",
                "aName" : "Volume"
            },
            {
                "aCode" : "aSpd",
                "aName" : "Speed"
            },
            {
                "aCode" : "aVc",
                "aName" : "Volume-to-Capacity Ratio"
            }
        ]
    }
]


data

[{'attributes': [{'aCode': 'aDist', 'aName': 'Distance'},
   {'aCode': 'aLanes', 'aName': 'Lanes'},
   {'aCode': 'aFt', 'aName': 'Functional Type'},
   {'aCode': 'aFtClass', 'aName': 'Function Group'},
   {'aCode': 'aCap1HL', 'aName': 'Capacity per Hour per Lane'},
   {'aCode': 'aCap1HL', 'aName': 'Capacity per Hour per Lane'},
   {'aCode': 'aFfSpd', 'aName': 'Free-flow Speed'},
   {'aCode': 'aVol', 'aName': 'Volume'},
   {'aCode': 'aSpd', 'aName': 'Speed'},
   {'aCode': 'aVc', 'aName': 'Volume-to-Capacity Ratio'}]}]

In [384]:
dfColKeys = pd.DataFrame([
    ['LINKS'      ,'DT', None , None, 'aLinks'  ],
    ['DIST_1WY'   ,'DT', None , None, 'aDist'   ],
    ['LANES'      ,'DT', None , None, 'aLanes'  ],
    ['FT'         ,'DT', None , None, 'aFt'     ],
    ['FTCLASS'    ,'DT', None , None, 'aFtClass'],
    ['CAP1HL'     ,'DT', None , None, 'aCap1HL' ],
    ['AM_VOL'     ,'DT', 'All', 'AM', 'aVol'    ],
    ['MD_VOL'     ,'DT', 'All', 'MD', 'aVol'    ],
    ['PM_VOL'     ,'DT', 'All', 'PM', 'aVol'    ],
    ['EV_VOL'     ,'DT', 'All', 'EV', 'aVol'    ],
    ['DY_VOL'     ,'DT', 'All', 'DY', 'aVol'    ],
    ['DY_LT'      ,'DT', 'LT' , 'DY', 'aVol'    ],
    ['DY_MD'      ,'DT', 'MD' , 'DY', 'aVol'    ],
    ['DY_HV'      ,'DT', 'HV' , 'DY', 'aVol'    ],
    ['FF_SPD'     ,'DT', None , None, 'aFfSpd'  ],
    ['AM_SPD'     ,'DT', None , 'AM', 'aSpd'    ],
    ['MD_SPD'     ,'DT', None , 'MD', 'aSpd'    ],
    ['PM_SPD'     ,'DT', None , 'PM', 'aSpd'    ],
    ['EV_SPD'     ,'DT', None , 'EV', 'aSpd'    ],
    ['DY_SPD'     ,'DT', None , 'DY', 'aSpd'    ],
    ['D1_LINKS'   ,'D1', None , None, 'aLinks'  ],
    ['D1_DIST'    ,'D1', None , None, 'aDist'   ],
    ['D1_LANES'   ,'D1', None , None, 'aLanes'  ],
    ['D1_FT'      ,'D1', None , None, 'aFt'     ],
    ['D1_FTCLASS' ,'D1', None , None, 'aFtClass'],
    ['D1_CAP1HL'  ,'D1', None , None, 'aCap1HL' ],
    ['D1_AM_VOL'  ,'D1', 'All', 'AM', 'aVol'    ],
    ['D1_MD_VOL'  ,'D1', 'All', 'MD', 'aVol'    ],
    ['D1_PM_VOL'  ,'D1', 'All', 'PM', 'aVol'    ],
    ['D1_EV_VOL'  ,'D1', 'All', 'EV', 'aVol'    ],
    ['D1_DY_VOL'  ,'D1', 'All', 'DY', 'aVol'    ],
    ['D1_DY_LT'   ,'D1', 'LT' , 'DY', 'aVol'    ],
    ['D1_DY_MD'   ,'D1', 'MD' , 'DY', 'aVol'    ],
    ['D1_DY_HV'   ,'D1', 'HV' , 'DY', 'aVol'    ],
    ['D1_FF_SPD'  ,'D1', None , None, 'aFfSpd'  ],
    ['D1_AM_SPD'  ,'D1', None , 'AM', 'aSpd'    ],
    ['D1_MD_SPD'  ,'D1', None , 'MD', 'aSpd'    ],
    ['D1_PM_SPD'  ,'D1', None , 'PM', 'aSpd'    ],
    ['D1_EV_SPD'  ,'D1', None , 'EV', 'aSpd'    ],
    ['D1_DY_SPD'  ,'D1', None , 'DY', 'aSpd'    ],
    ['D2_LINKS'   ,'D2', None , None, 'aLinks'  ],
    ['D2_DIST'    ,'D2', None , None, 'aDist'   ],
    ['D2_LANES'   ,'D2', None , None, 'aLanes'  ],
    ['D2_FT'      ,'D2', None , None, 'aFt'     ],
    ['D2_FTCLASS' ,'D2', None , None, 'aFtClass'],
    ['D2_CAP1HL'  ,'D2', None , None, 'aCap1HL' ],
    ['D2_AM_VOL'  ,'D2', 'All', 'AM', 'aVol'    ],
    ['D2_MD_VOL'  ,'D2', 'All', 'MD', 'aVol'    ],
    ['D2_PM_VOL'  ,'D2', 'All', 'PM', 'aVol'    ],
    ['D2_EV_VOL'  ,'D2', 'All', 'EV', 'aVol'    ],
    ['D2_DY_VOL'  ,'D2', 'All', 'DY', 'aVol'    ],
    ['D2_DY_LT'   ,'D2', 'LT' , 'DY', 'aVol'    ],
    ['D2_DY_MD'   ,'D2', 'MD' , 'DY', 'aVol'    ],
    ['D2_DY_HV'   ,'D2', 'HV' , 'DY', 'aVol'    ],
    ['D2_FF_SPD'  ,'D2', None , None, 'aFfSpd'  ],
    ['D2_AM_SPD'  ,'D2', None , 'AM', 'aSpd'    ],
    ['D2_MD_SPD'  ,'D2', None , 'MD', 'aSpd'    ],
    ['D2_PM_SPD'  ,'D2', None , 'PM', 'aSpd'    ],
    ['D2_EV_SPD'  ,'D2', None , 'EV', 'aSpd'    ],
    ['D2_DY_SPD'  ,'D2', None , 'DY', 'aSpd'    ],
    # calculated in this notebook - TO BE REPLACED BY VOYAGER CODE IN FUTURE
    ['AM_VC'      ,'DT', None , 'AM', 'aVc'     ],
    ['MD_VC'      ,'DT', None , 'MD', 'aVc'     ],
    ['PM_VC'      ,'DT', None , 'PM', 'aVc'     ],
    ['EV_VC'      ,'DT', None , 'EV', 'aVc'     ],
    ['DY_VC'      ,'DT', None , 'DY', 'aVc'     ],
    ['D1_AM_VC'   ,'D1', None , 'AM', 'aVc'     ],
    ['D1_MD_VC'   ,'D1', None , 'MD', 'aVc'     ],
    ['D1_PM_VC'   ,'D1', None , 'PM', 'aVc'     ],
    ['D1_EV_VC'   ,'D1', None , 'EV', 'aVc'     ],
    ['D1_DY_VC'   ,'D1', None , 'DY', 'aVc'     ],
    ['D2_AM_VC'   ,'D2', None , 'AM', 'aVc'     ],
    ['D2_MD_VC'   ,'D2', None , 'MD', 'aVc'     ],
    ['D2_PM_VC'   ,'D2', None , 'PM', 'aVc'     ],
    ['D2_EV_VC'   ,'D2', None , 'EV', 'aVc'     ],
    ['D2_DY_VC'   ,'D2', None , 'DY', 'aVc'     ],
], columns=('col','fDir','fVeh','fTod','att'))

dfColKeys

         col fDir  fVeh  fTod       att
0      LINKS   DT  None  None    aLinks
1   DIST_1WY   DT  None  None     aDist
2      LANES   DT  None  None    aLanes
3         FT   DT  None  None       aFt
4    FTCLASS   DT  None  None  aFtClass
..       ...  ...   ...   ...       ...
70  D2_AM_VC   D2  None    AM       aVc
71  D2_MD_VC   D2  None    MD       aVc
72  D2_PM_VC   D2  None    PM       aVc
73  D2_EV_VC   D2  None    EV       aVc
74  D2_DY_VC   D2  None    DY       aVc

[75 rows x 5 columns]

In [385]:
dfScn = pd.read_json(scnJson)
display(dfScn)
display(dfScn.dtypes)

   modVersion   scnGroup  scnYear
0        v900       Base     2019
1        v900       Base     2023
2        v900        TIP     2028
3        v900        RTP     2032
4        v900        RTP     2042
5        v900        RTP     2050
6        v900    NoBuild     2032
7        v900    NoBuild     2042
8        v900    NoBuild     2050
9        v900      Needs     2032
10       v900      Needs     2042
11       v900      Needs     2050
12       v900      Needs     2042
13       v900  Needs MAG     2050

modVersion    object
scnGroup      object
scnYear        int64
dtype: object

In [386]:
# create folders
# Define a root directory where you want to create subfolders
root_dir = './_site/data/scnData'

# Ensure the root directory exists
if not os.path.exists(root_dir):
    os.makedirs(root_dir)

# Loop through the dataframe and create subfolders
for index, row in dfScn.iterrows():
    folder_name = f"{row['modVersion']}__{row['scnGroup']}__{row['scnYear']}"
    full_path = os.path.join(root_dir, folder_name)
    
    if not os.path.exists(full_path):
        os.makedirs(full_path)

In [387]:
import pandas as pd
import os
import glob

# Define the subfolder path
subfolder_path = './data/segSummaries/'

# Use glob to get all the files ending with "_Summary_SEGID.csv"
file_paths = glob.glob(os.path.join(subfolder_path, "*.csv"))

# Create an empty list to store dataframes
dfs = []

# Loop through the files, parse filename, and read them into dataframes
for file_path in file_paths:
    # Get filename without extension
    filename = os.path.splitext(os.path.basename(file_path))[0]
    
    # Split filename based on double underscore
    modVersion, scnGroup, scnYear = filename.split('__')
    
    # Read the CSV into a dataframe
    df = pd.read_csv(file_path)
    
    # Add new columns with values from filename
    df['modVersion'] = modVersion
    df['scnGroup'] = scnGroup
    df['scnYear'] = scnYear
    
    dfs.append(df)

# If you want to concatenate all the dataframes into a single dataframe
dfCombined = pd.concat(dfs, ignore_index=True)
dfCombined['scnYear'] = dfCombined['scnYear'].astype('int64')
dfCombined

,SEGIDIDX,SEGID,SUBAREAID,CO_FIPS,AREATYPE,ATYPENAME,LINKS,DIST_1WY,LANES,FT,...,D2_DY_HV,D2_FF_SPD,D2_AM_SPD,D2_MD_SPD,D2_PM_SPD,D2_EV_SPD,D2_DY_SPD,modVersion,scnGroup,scnYear
0,1,0006_146.9,1.0,49.0,1.0,Rural,20,8.789,2.0,2.0,...,45.8,58.0,58.0,58.0,58.0,58.0,58.0,v900,Base,2019
1,2,0006_149.9,1.0,49.0,1.0,Rural,2,0.621,2.0,2.0,...,40.1,58.0,58.0,58.0,58.0,58.0,58.0,v900,Base,2019
2,3,0006_150.6,1.0,49.0,1.0,Rural,8,1.976,2.0,2.0,...,44.8,58.0,58.0,58.0,58.0,58.0,58.0,v900,Base,2019
3,4,0006_152.6,1.0,49.0,1.0,Rural,2,0.374,2.0,3.0,...,76.1,55.0,55.0,55.0,55.0,55.0,55.0,v900,Base,2019
4,5,0006_152.9,1.0,49.0,1.0,Rural,6,3.060,2.0,2.0,...,122.7,57.7,57.7,57.7,57.6,57.7,57.7,v900,Base,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50292,3809,WFRC_8261,1.0,35.0,4.0,Urban,4,0.495,2.0,4.0,...,108.9,28.0,28.0,27.9,27.9,28.0,27.9,v900,TIP,2028
50293,3810,WFRC_8263,1.0,35.0,3.0,Suburban,4,0.444,2.0,4.0,...,102.9,34.0,33.9,33.5,30.5,34.0,32.6,v900,TIP,2028
50294,3811,WFRC_8264,1.0,11.0,3.0,Suburban,4,0.419,4.0,3.0,...,321.4,35.0,35.0,35.0,34.9,35.0,35.0,v900,TIP,2028
50295,3812,WFRC_8265,1.0,35.0,4.0,Urban,2,0.348,2.0,4.0,...,47.7,28.0,28.0,28.0,27.9,28.0,27.9,v900,TIP,2028
50296,3813,WFRC_8266,1.0,35.0,4.0,Urban,2,0.178,2.0,4.0,...,136.9,28.0,27.9,27.8,25.8,28.0,27.1,v900,TIP,2028

In [388]:
# CALCULATE VC -- TO BE REPLACED IN FUTURE
_df = dfCombined

def calculate_cap(df, prefix, multiplier):
    factors = {'AM': 3, 'MD': 6, 'PM': 3, 'EV': 12}
    for period, factor in factors.items():
        df[f'{prefix}{period}_VC'] = df[f'{prefix}{period}_VOL'] / (df[f'{multiplier}'] * df['LANES'] * factor)

calculate_cap(_df, ''   ,    'CAP1HL')
calculate_cap(_df, 'D1_', 'D1_CAP1HL')
calculate_cap(_df, 'D2_', 'D2_CAP1HL')

_df['D1_DY_VC'] = _df[['D1_AM_VC', 'D1_MD_VC', 'D1_PM_VC', 'D1_EV_VC']].max(axis=1)
_df['D2_DY_VC'] = _df[['D2_AM_VC', 'D2_MD_VC', 'D2_PM_VC', 'D2_EV_VC']].max(axis=1)
_df['DY_VC'   ] = _df[['D1_DY_VC', 'D2_DY_VC']].max(axis=1)

dfCombined_withVc = _df

In [389]:
dfCombined_melt = dfCombined_withVc.melt(id_vars=['SEGID','modVersion','scnGroup','scnYear'], value_vars=dfColKeys['col'].tolist(), var_name='col', value_name='val')

dfCombined_melt

              SEGID modVersion scnGroup  scnYear       col       val
0        0006_146.9       v900     Base     2019     LINKS        20
1        0006_149.9       v900     Base     2019     LINKS         2
2        0006_150.6       v900     Base     2019     LINKS         8
3        0006_152.6       v900     Base     2019     LINKS         2
4        0006_152.9       v900     Base     2019     LINKS         6
...             ...        ...      ...      ...       ...       ...
3772270   WFRC_8261       v900      TIP     2028  D2_DY_VC  0.080041
3772271   WFRC_8263       v900      TIP     2028  D2_DY_VC  0.270282
3772272   WFRC_8264       v900      TIP     2028  D2_DY_VC  0.119075
3772273   WFRC_8265       v900      TIP     2028  D2_DY_VC  0.091068
3772274   WFRC_8266       v900      TIP     2028  D2_DY_VC  0.233094

[3772275 rows x 6 columns]

In [390]:
dfCombined_melt_withkeys = pd.DataFrame.merge(dfCombined_melt, dfColKeys, on='col')
dfCombined_melt_withkeys

,SEGID,modVersion,scnGroup,scnYear,col,val,fDir,fVeh,fTod,att
0,0006_146.9,v900,Base,2019,LINKS,20,DT,None,None,aLinks
1,0006_149.9,v900,Base,2019,LINKS,2,DT,None,None,aLinks
2,0006_150.6,v900,Base,2019,LINKS,8,DT,None,None,aLinks
3,0006_152.6,v900,Base,2019,LINKS,2,DT,None,None,aLinks
4,0006_152.9,v900,Base,2019,LINKS,6,DT,None,None,aLinks
...,...,...,...,...,...,...,...,...,...,...
3772270,WFRC_8261,v900,TIP,2028,D2_DY_VC,0.080041,D2,None,DY,aVc
3772271,WFRC_8263,v900,TIP,2028,D2_DY_VC,0.270282,D2,None,DY,aVc
3772272,WFRC_8264,v900,TIP,2028,D2_DY_VC,0.119075,D2,None,DY,aVc
3772273,WFRC_8265,v900,TIP,2028,D2_DY_VC,0.091068,D2,None,DY,aVc
3772274,WFRC_8266,v900,TIP,2028,D2_DY_VC,0.233094,D2,None,DY,aVc

In [391]:
dfCombined_melt_withkeys_pivot_atts = dfCombined_melt_withkeys.pivot(index=[col for col in dfCombined_melt_withkeys.columns if col not in ['att','val','col']], columns="att", values="val")
dfCombined_melt_withkeys_pivot_atts = dfCombined_melt_withkeys_pivot_atts.reset_index()
#dfCombined_melt_withkeys_pivot_atts = dfCombined_melt_withkeys_pivot_atts.fillna('blank')
dfCombined_melt_withkeys_pivot_atts

att,SEGID,modVersion,scnGroup,scnYear,fDir,fVeh,fTod,aCap1HL,aDist,aFfSpd,aFt,aFtClass,aLanes,aLinks,aSpd,aVc,aVol
0,0006_146.9,v900,Base,2019,D1,NaN,NaN,1065,8.789,58.0,2.0,Principal Arterial,1.0,10,NaN,NaN,NaN
1,0006_146.9,v900,Base,2019,D1,NaN,AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58.0,0.031424,NaN
2,0006_146.9,v900,Base,2019,D1,NaN,DY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58.0,0.031424,NaN
3,0006_146.9,v900,Base,2019,D1,NaN,EV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58.0,0.007328,NaN
4,0006_146.9,v900,Base,2019,D1,NaN,MD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58.0,0.020759,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2112469,WFRC_8266,v900,TIP,2028,DT,All,MD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1848.3
2112470,WFRC_8266,v900,TIP,2028,DT,All,PM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1768.0
2112471,WFRC_8266,v900,TIP,2028,DT,HV,DY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,315.9
2112472,WFRC_8266,v900,TIP,2028,DT,LT,DY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.3
2112473,WFRC_8266,v900,TIP,2028,DT,MD,DY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,594.3

In [392]:
fCols = [col for col in dfCombined_melt_withkeys.columns if col.startswith('f')]

_df = dfCombined_melt_withkeys_pivot_atts.copy()

_df[fCols] = _df[fCols].fillna('')

dfFilters = _df[fCols].drop_duplicates()

_dfFilters = dfFilters

# Convert the values to binary form
binary_dfFilters = _dfFilters.applymap(lambda x: 0 if x=='' else 1)

# Get unique rows of combinations
unique_combinations = binary_dfFilters.drop_duplicates()

# Convert the unique combinations to a list of tuples
combinations_list = list(unique_combinations.itertuples(index=False, name=None))

# Define a function to convert to binary
def is_empty_or_not(value):
    return 0 if value=='' else 1

dfFilterWithAttributes = pd.DataFrame()

for combination in combinations_list:
    columns_with_value_1 = [col for idx, col in enumerate(fCols) if combination[idx] == 1]
    concatenated_string = '_'.join(columns_with_value_1)

    print(concatenated_string)
    
    condition = (
        (_df['fDir'].apply(is_empty_or_not) == combination[0]) &
        (_df['fVeh'].apply(is_empty_or_not) == combination[1]) &
        (_df['fTod'].apply(is_empty_or_not) == combination[2])
    )
    _filtered_df = _df[condition].copy()
    #display(_filtered_df)

    # Remove columns where all values are NaN
    _filtered_df_noNA = _filtered_df.dropna(axis=1, how='all')
    #display(_filtered_df_noNA)

    fColsToDrop = [col for col in _filtered_df_noNA.columns if col.startswith('f') and (_filtered_df_noNA[col] == '').all()]

    # Drop the identified columns
    _df2 = _filtered_df_noNA.drop(columns=fColsToDrop)
    display(_df2)

    # Get list of columns that begin with "a", create a dataframe with them and then explode and concat
    aCols = [col for col in _filtered_df_noNA.columns if col.startswith('a')]
    new_data = pd.DataFrame([{"filterGroup": concatenated_string, "aCode": aCols}])
    new_data = new_data.explode('aCode').reset_index(drop=True)
    dfFilterWithAttributes = pd.concat([dfFilterWithAttributes, new_data], ignore_index=True)

    # Loop through scenarios in dfScn
    for _, row in dfScn.iterrows():
        #print(row['modVersion'] + row['scnGroup'] + str(row['scnYear']))
        # Filter the main dataframe based on the scenario
        _df2_filtered = _df2[
            (_df2['modVersion'] == row['modVersion']) & 
            (_df2['scnGroup'] == row['scnGroup']) & 
            (_df2['scnYear'] == row['scnYear'])
        ].copy()
        
        # Create the filename based on the scenario and directory structure
        folder_name = f"{row['modVersion']}__{row['scnGroup']}__{row['scnYear']}"
        full_path = os.path.join(base_dir, folder_name, 'roadsegsummary__' + concatenated_string + '.json')

        _df2_filtered.drop(columns=['modVersion','scnGroup','scnYear'], inplace=True)

        # Export the filtered dataframe to a json file
        _df2_filtered = _df2_filtered.rename(columns={'SEGID':'id'})
        #_df2_filtered.to_json(full_path, orient='records', lines=True)


# Now, filtered_dfs contains a list of DataFrames, each filtered by a unique combination

fDir

att,SEGID,modVersion,scnGroup,scnYear,fDir,aCap1HL,aDist,aFfSpd,aFt,aFtClass,aLanes,aLinks
0,0006_146.9,v900,Base,2019,D1,1065,8.789,58.0,2.0,Principal Arterial,1.0,10
14,0006_146.9,v900,Base,2019,D2,1065,8.789,58.0,2.0,Principal Arterial,1.0,10
28,0006_146.9,v900,Base,2019,DT,1065,8.789,58.0,2.0,Principal Arterial,2.0,20
42,0006_146.9,v900,Base,2023,D1,1065,8.789,58.0,2.0,Principal Arterial,1.0,10
56,0006_146.9,v900,Base,2023,D2,1065,8.789,58.0,2.0,Principal Arterial,1.0,10
...,...,...,...,...,...,...,...,...,...,...,...,...
2112404,WFRC_8266,v900,RTP,2050,D2,696,0.178,28.0,4.0,Collector,1.0,1
2112418,WFRC_8266,v900,RTP,2050,DT,696,0.178,28.0,4.0,Collector,2.0,2
2112432,WFRC_8266,v900,TIP,2028,D1,696,0.178,28.0,4.0,Collector,1.0,1
2112446,WFRC_8266,v900,TIP,2028,D2,696,0.178,28.0,4.0,Collector,1.0,1
2112460,WFRC_8266,v900,TIP,2028,DT,696,0.178,28.0,4.0,Collector,2.0,2

fDir_fTod

att           SEGID modVersion scnGroup  scnYear fDir fTod  aSpd       aVc
1        0006_146.9       v900     Base     2019   D1   AM  58.0  0.031424
2        0006_146.9       v900     Base     2019   D1   DY  58.0  0.031424
3        0006_146.9       v900     Base     2019   D1   EV  58.0  0.007328
4        0006_146.9       v900     Base     2019   D1   MD  58.0  0.020759
5        0006_146.9       v900     Base     2019   D1   PM  58.0   0.03011
...             ...        ...      ...      ...  ...  ...   ...       ...
2112461   WFRC_8266       v900      TIP     2028   DT   AM  27.8  0.188003
2112462   WFRC_8266       v900      TIP     2028   DT   DY  27.3  0.233094
2112463   WFRC_8266       v900      TIP     2028   DT   EV  28.0   0.06705
2112464   WFRC_8266       v900      TIP     2028   DT   MD  27.8    0.2213
2112465   WFRC_8266       v900      TIP     2028   DT   PM  26.2  0.423372

[754455 rows x 8 columns]

fDir_fVeh_fTod

att           SEGID modVersion scnGroup  scnYear fDir fVeh fTod    aVol
6        0006_146.9       v900     Base     2019   D1  All   AM   200.8
7        0006_146.9       v900     Base     2019   D1  All   DY   845.9
8        0006_146.9       v900     Base     2019   D1  All   EV   187.3
9        0006_146.9       v900     Base     2019   D1  All   MD   265.3
10       0006_146.9       v900     Base     2019   D1  All   PM   192.4
...             ...        ...      ...      ...  ...  ...  ...     ...
2112469   WFRC_8266       v900      TIP     2028   DT  All   MD  1848.3
2112470   WFRC_8266       v900      TIP     2028   DT  All   PM  1768.0
2112471   WFRC_8266       v900      TIP     2028   DT   HV   DY   315.9
2112472   WFRC_8266       v900      TIP     2028   DT   LT   DY  1000.3
2112473   WFRC_8266       v900      TIP     2028   DT   MD   DY   594.3

[1207128 rows x 8 columns]

In [393]:
dfFilterWithAttributes

      filterGroup     aCode
0            fDir   aCap1HL
1            fDir     aDist
2            fDir    aFfSpd
3            fDir       aFt
4            fDir  aFtClass
5            fDir    aLanes
6            fDir    aLinks
7       fDir_fTod      aSpd
8       fDir_fTod       aVc
9  fDir_fVeh_fTod      aVol

In [394]:
# ADD FILTER GROUP TO ATTRIBUTES

# Convert DataFrame into a dictionary for efficient lookup
lookup_dict = dfFilterWithAttributes.set_index('aCode')['filterGroup'].to_dict()

# Loop through the attributes in the data object and update with the filterGroup
for attribute in data[0]['attributes']:
    aCode_value = attribute['aCode']
    if aCode_value in lookup_dict:
        attribute['filterGroup'] = lookup_dict[aCode_value]

display(data)

[{'attributes': [{'aCode': 'aDist',
    'aName': 'Distance',
    'filterGroup': 'fDir'},
   {'aCode': 'aLanes', 'aName': 'Lanes', 'filterGroup': 'fDir'},
   {'aCode': 'aFt', 'aName': 'Functional Type', 'filterGroup': 'fDir'},
   {'aCode': 'aFtClass', 'aName': 'Function Group', 'filterGroup': 'fDir'},
   {'aCode': 'aCap1HL',
    'aName': 'Capacity per Hour per Lane',
    'filterGroup': 'fDir'},
   {'aCode': 'aCap1HL',
    'aName': 'Capacity per Hour per Lane',
    'filterGroup': 'fDir'},
   {'aCode': 'aFfSpd', 'aName': 'Free-flow Speed', 'filterGroup': 'fDir'},
   {'aCode': 'aVol', 'aName': 'Volume', 'filterGroup': 'fDir_fVeh_fTod'},
   {'aCode': 'aSpd', 'aName': 'Speed', 'filterGroup': 'fDir_fTod'},
   {'aCode': 'aVc',
    'aName': 'Volume-to-Capacity Ratio',
    'filterGroup': 'fDir_fTod'}]}]