In [116]:
import pandas as pd
import os

In [117]:
segSummaries =  "A:/1 - TDM/3 - Model Dev/1 - WF/1 - Official Release/v9x/v9.0/WF TDM v9.0 - official/Scenarios/_roadwaysegsummaries"
scnJson = "_site/data/scnData/scenarios.json"

In [118]:
# attributes for road seg summaries
dfAttributes = pd.DataFrame([
    ["aLinks"  ,"Links"                     ],
#   ["aDist"   ,"Distance"                  ],
    ["aLanes"  ,"Lanes"                     ],
    ["aFt"     ,"Functional Type"           ],
    ["aFtClass","Functional Class"          ],
    ["aCap1HL" ,"Capacity per Hour per Lane"],
    ["aFfSpd"  ,"Free-flow Speed"           ],
    ["aVol"    ,"Volume"                    ],
    ["aSpd"    ,"Speed"                     ],
    ["aVc"     ,"Volume-to-Capacity Ratio"  ]
], columns=('aCode','aName'))

display(dfAttributes)

dfFilters = pd.DataFrame([
    ["fDir"  ,"Direction"   , "select"],
    ["fTod"  ,"Time of Day" , "select"],
    ["fVeh"  ,"Vehicle Type", "select"]
], columns=('fCode','fName','fWidget'))

display(dfFilters)

      aCode                       aName
0    aLinks                       Links
1    aLanes                       Lanes
2       aFt             Functional Type
3  aFtClass            Functional Class
4   aCap1HL  Capacity per Hour per Lane
5    aFfSpd             Free-flow Speed
6      aVol                      Volume
7      aSpd                       Speed
8       aVc    Volume-to-Capacity Ratio

  fCode         fName fWidget
0  fDir     Direction  select
1  fTod   Time of Day  select
2  fVeh  Vehicle Type  select

In [119]:
# MAKE SURE ONLY COLUMNS WITH LOWER-CASE "f" ARE FILTER COLUMNS AND LOWER-CASE "a" ARE ATTRIBUTE COLUMNS

dfColKeys = pd.DataFrame([
    ['LINKS'      ,'DT', None , None, 'aLinks'  ],
#   ['DIST_1WY'   ,'DT', None , None, 'aDist'   ], # Distance is not actual distance of segment but only links defined with SEGID, for freeways this can be pretty different
    ['LANES'      ,'DT', None , None, 'aLanes'  ],
    ['FT'         ,'DT', None , None, 'aFt'     ],
    ['FTCLASS'    ,'DT', None , None, 'aFtClass'],
    ['CAP1HL'     ,'DT', None , None, 'aCap1HL' ],
    ['MD_VOL'     ,'DT', 'All', 'MD', 'aVol'    ],
    ['PM_VOL'     ,'DT', 'All', 'PM', 'aVol'    ],
    ['EV_VOL'     ,'DT', 'All', 'EV', 'aVol'    ],
    ['DY_LT'      ,'DT', 'LT' , 'DY', 'aVol'    ],
    ['DY_MD'      ,'DT', 'MD' , 'DY', 'aVol'    ],
    ['DY_HV'      ,'DT', 'HV' , 'DY', 'aVol'    ],
    ['FF_SPD'     ,'DT', None , None, 'aFfSpd'  ],
    ['AM_SPD'     ,'DT', None , 'AM', 'aSpd'    ],
    ['MD_SPD'     ,'DT', None , 'MD', 'aSpd'    ],
    ['PM_SPD'     ,'DT', None , 'PM', 'aSpd'    ],
    ['EV_SPD'     ,'DT', None , 'EV', 'aSpd'    ],
    ['DY_SPD'     ,'DT', None , 'DY', 'aSpd'    ],
    ['D1_LINKS'   ,'D1', None , None, 'aLinks'  ],
#   ['D1_DIST'    ,'D1', None , None, 'aDist'   ], # Distance is not actual distance of segment but only links defined with SEGID, for freeways this can be pretty different
    ['D1_LANES'   ,'D1', None , None, 'aLanes'  ],
    ['D1_FT'      ,'D1', None , None, 'aFt'     ],
    ['D1_FTCLASS' ,'D1', None , None, 'aFtClass'],
    ['D1_CAP1HL'  ,'D1', None , None, 'aCap1HL' ],
    ['D1_AM_VOL'  ,'D1', 'All', 'AM', 'aVol'    ],
    ['D1_MD_VOL'  ,'D1', 'All', 'MD', 'aVol'    ],
    ['D1_PM_VOL'  ,'D1', 'All', 'PM', 'aVol'    ],
    ['D1_EV_VOL'  ,'D1', 'All', 'EV', 'aVol'    ],
    ['D1_DY_VOL'  ,'D1', 'All', 'DY', 'aVol'    ],
    ['D1_DY_LT'   ,'D1', 'LT' , 'DY', 'aVol'    ],
    ['D1_DY_MD'   ,'D1', 'MD' , 'DY', 'aVol'    ],
    ['D1_DY_HV'   ,'D1', 'HV' , 'DY', 'aVol'    ],
    ['D1_FF_SPD'  ,'D1', None , None, 'aFfSpd'  ],
    ['D1_AM_SPD'  ,'D1', None , 'AM', 'aSpd'    ],
    ['D1_MD_SPD'  ,'D1', None , 'MD', 'aSpd'    ],
    ['D1_PM_SPD'  ,'D1', None , 'PM', 'aSpd'    ],
    ['D1_EV_SPD'  ,'D1', None , 'EV', 'aSpd'    ],
    ['D1_DY_SPD'  ,'D1', None , 'DY', 'aSpd'    ],
    ['D2_LINKS'   ,'D2', None , None, 'aLinks'  ],
#   ['D2_DIST'    ,'D2', None , None, 'aDist'   ], # Distance is not actual distance of segment but only links defined with SEGID, for freeways this can be pretty different
    ['D2_LANES'   ,'D2', None , None, 'aLanes'  ],
    ['D2_FT'      ,'D2', None , None, 'aFt'     ],
    ['D2_FTCLASS' ,'D2', None , None, 'aFtClass'],
    ['D2_CAP1HL'  ,'D2', None , None, 'aCap1HL' ],
    ['D2_AM_VOL'  ,'D2', 'All', 'AM', 'aVol'    ],
    ['D2_MD_VOL'  ,'D2', 'All', 'MD', 'aVol'    ],
    ['D2_PM_VOL'  ,'D2', 'All', 'PM', 'aVol'    ],
    ['D2_EV_VOL'  ,'D2', 'All', 'EV', 'aVol'    ],
    ['D2_DY_VOL'  ,'D2', 'All', 'DY', 'aVol'    ],
    ['D2_DY_LT'   ,'D2', 'LT' , 'DY', 'aVol'    ],
    ['D2_DY_MD'   ,'D2', 'MD' , 'DY', 'aVol'    ],
    ['D2_DY_HV'   ,'D2', 'HV' , 'DY', 'aVol'    ],
    ['D2_FF_SPD'  ,'D2', None , None, 'aFfSpd'  ],
    ['D2_AM_SPD'  ,'D2', None , 'AM', 'aSpd'    ],
    ['D2_MD_SPD'  ,'D2', None , 'MD', 'aSpd'    ],
    ['D2_PM_SPD'  ,'D2', None , 'PM', 'aSpd'    ],
    ['D2_EV_SPD'  ,'D2', None , 'EV', 'aSpd'    ],
    ['D2_DY_SPD'  ,'D2', None , 'DY', 'aSpd'    ],
    # calculated in this notebook - TO BE REPLACED BY VOYAGER CODE IN FUTURE
    ['AM_VC'      ,'DT', None , 'AM', 'aVc'     ],
    ['MD_VC'      ,'DT', None , 'MD', 'aVc'     ],
    ['PM_VC'      ,'DT', None , 'PM', 'aVc'     ],
    ['EV_VC'      ,'DT', None , 'EV', 'aVc'     ],
    ['DY_VC'      ,'DT', None , 'DY', 'aVc'     ],
    ['D1_AM_VC'   ,'D1', None , 'AM', 'aVc'     ],
    ['D1_MD_VC'   ,'D1', None , 'MD', 'aVc'     ],
    ['D1_PM_VC'   ,'D1', None , 'PM', 'aVc'     ],
    ['D1_EV_VC'   ,'D1', None , 'EV', 'aVc'     ],
    ['D1_DY_VC'   ,'D1', None , 'DY', 'aVc'     ],
    ['D2_AM_VC'   ,'D2', None , 'AM', 'aVc'     ],
    ['D2_MD_VC'   ,'D2', None , 'MD', 'aVc'     ],
    ['D2_PM_VC'   ,'D2', None , 'PM', 'aVc'     ],
    ['D2_EV_VC'   ,'D2', None , 'EV', 'aVc'     ],
    ['D2_DY_VC'   ,'D2', None , 'DY', 'aVc'     ]
], columns=('col','fDir','fVeh','fTod','aCode'))

dfColKeys

         col fDir  fVeh  fTod     aCode
0      LINKS   DT  None  None    aLinks
1      LANES   DT  None  None    aLanes
2         FT   DT  None  None       aFt
3    FTCLASS   DT  None  None  aFtClass
4     CAP1HL   DT  None  None   aCap1HL
..       ...  ...   ...   ...       ...
65  D2_AM_VC   D2  None    AM       aVc
66  D2_MD_VC   D2  None    MD       aVc
67  D2_PM_VC   D2  None    PM       aVc
68  D2_EV_VC   D2  None    EV       aVc
69  D2_DY_VC   D2  None    DY       aVc

[70 rows x 5 columns]

In [120]:
dfScn = pd.read_json(scnJson)
display(dfScn)
display(dfScn.dtypes)

   modVersion   scnGroup  scnYear
0        v900       Base     2019
1        v900       Base     2023
2        v900        TIP     2028
3        v900        RTP     2032
4        v900        RTP     2042
5        v900        RTP     2050
6        v900    NoBuild     2032
7        v900    NoBuild     2042
8        v900    NoBuild     2050
9        v900      Needs     2032
10       v900      Needs     2042
11       v900      Needs     2050
12       v900      Needs     2042
13       v900  Needs MAG     2050

modVersion    object
scnGroup      object
scnYear        int64
dtype: object

In [121]:
# create folders
# Define a root directory where you want to create subfolders
root_dir = './_site/data/scnData'

# Ensure the root directory exists
if not os.path.exists(root_dir):
    os.makedirs(root_dir)

# Loop through the dataframe and create subfolders
for index, row in dfScn.iterrows():
    folder_name = f"{row['modVersion']}__{row['scnGroup']}__{row['scnYear']}"
    full_path = os.path.join(root_dir, folder_name)
    
    if not os.path.exists(full_path):
        os.makedirs(full_path)

In [122]:
import pandas as pd
import os
import glob

# Define the subfolder path
subfolder_path = './data/segSummaries/'

# Use glob to get all the files ending with "_Summary_SEGID.csv"
file_paths = glob.glob(os.path.join(subfolder_path, "*.csv"))

# Create an empty list to store dataframes
dfs = []

# Loop through the files, parse filename, and read them into dataframes
for file_path in file_paths:
    # Get filename without extension
    filename = os.path.splitext(os.path.basename(file_path))[0]
    
    # Split filename based on double underscore
    modVersion, scnGroup, scnYear = filename.split('__')
    
    # Read the CSV into a dataframe
    df = pd.read_csv(file_path)
    
    # Add new columns with values from filename
    df['modVersion'] = modVersion
    df['scnGroup'] = scnGroup
    df['scnYear'] = scnYear
    
    dfs.append(df)

# If you want to concatenate all the dataframes into a single dataframe
dfCombined = pd.concat(dfs, ignore_index=True)
dfCombined['scnYear'] = dfCombined['scnYear'].astype('int64')
dfCombined

,SEGIDIDX,SEGID,SUBAREAID,CO_FIPS,AREATYPE,ATYPENAME,LINKS,DIST_1WY,LANES,FT,...,D2_DY_HV,D2_FF_SPD,D2_AM_SPD,D2_MD_SPD,D2_PM_SPD,D2_EV_SPD,D2_DY_SPD,modVersion,scnGroup,scnYear
0,1,0006_146.9,1.0,49.0,1.0,Rural,20,8.789,2.0,2.0,...,45.8,58.0,58.0,58.0,58.0,58.0,58.0,v900,Base,2019
1,2,0006_149.9,1.0,49.0,1.0,Rural,2,0.621,2.0,2.0,...,40.1,58.0,58.0,58.0,58.0,58.0,58.0,v900,Base,2019
2,3,0006_150.6,1.0,49.0,1.0,Rural,8,1.976,2.0,2.0,...,44.8,58.0,58.0,58.0,58.0,58.0,58.0,v900,Base,2019
3,4,0006_152.6,1.0,49.0,1.0,Rural,2,0.374,2.0,3.0,...,76.1,55.0,55.0,55.0,55.0,55.0,55.0,v900,Base,2019
4,5,0006_152.9,1.0,49.0,1.0,Rural,6,3.060,2.0,2.0,...,122.7,57.7,57.7,57.7,57.6,57.7,57.7,v900,Base,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50292,3809,WFRC_8261,1.0,35.0,4.0,Urban,4,0.495,2.0,4.0,...,108.9,28.0,28.0,27.9,27.9,28.0,27.9,v900,TIP,2028
50293,3810,WFRC_8263,1.0,35.0,3.0,Suburban,4,0.444,2.0,4.0,...,102.9,34.0,33.9,33.5,30.5,34.0,32.6,v900,TIP,2028
50294,3811,WFRC_8264,1.0,11.0,3.0,Suburban,4,0.419,4.0,3.0,...,321.4,35.0,35.0,35.0,34.9,35.0,35.0,v900,TIP,2028
50295,3812,WFRC_8265,1.0,35.0,4.0,Urban,2,0.348,2.0,4.0,...,47.7,28.0,28.0,28.0,27.9,28.0,27.9,v900,TIP,2028
50296,3813,WFRC_8266,1.0,35.0,4.0,Urban,2,0.178,2.0,4.0,...,136.9,28.0,27.9,27.8,25.8,28.0,27.1,v900,TIP,2028

In [123]:
# CALCULATE VC -- TO BE REPLACED IN FUTURE
_df = dfCombined

def calculate_cap(df, prefix, multiplier):
    factors = {'AM': 3, 'MD': 6, 'PM': 3, 'EV': 12}
    for period, factor in factors.items():
        df[f'{prefix}{period}_VC'] = round(df[f'{prefix}{period}_VOL'] / (df[f'{multiplier}'] * df['LANES'] * factor),2)

calculate_cap(_df, ''   ,    'CAP1HL')
calculate_cap(_df, 'D1_', 'D1_CAP1HL')
calculate_cap(_df, 'D2_', 'D2_CAP1HL')

_df['D1_DY_VC'] = _df[['D1_AM_VC', 'D1_MD_VC', 'D1_PM_VC', 'D1_EV_VC']].max(axis=1)
_df['D2_DY_VC'] = _df[['D2_AM_VC', 'D2_MD_VC', 'D2_PM_VC', 'D2_EV_VC']].max(axis=1)
_df['DY_VC'   ] = _df[['D1_DY_VC', 'D2_DY_VC']].max(axis=1)

dfCombined_withVc = _df

In [124]:
dfCombined_melt = dfCombined_withVc.melt(id_vars=['SEGID','modVersion','scnGroup','scnYear'], value_vars=dfColKeys['col'].tolist(), var_name='col', value_name='val')

dfCombined_melt

              SEGID modVersion scnGroup  scnYear       col   val
0        0006_146.9       v900     Base     2019     LINKS    20
1        0006_149.9       v900     Base     2019     LINKS     2
2        0006_150.6       v900     Base     2019     LINKS     8
3        0006_152.6       v900     Base     2019     LINKS     2
4        0006_152.9       v900     Base     2019     LINKS     6
...             ...        ...      ...      ...       ...   ...
3520785   WFRC_8261       v900      TIP     2028  D2_DY_VC  0.08
3520786   WFRC_8263       v900      TIP     2028  D2_DY_VC  0.27
3520787   WFRC_8264       v900      TIP     2028  D2_DY_VC  0.12
3520788   WFRC_8265       v900      TIP     2028  D2_DY_VC  0.09
3520789   WFRC_8266       v900      TIP     2028  D2_DY_VC  0.23

[3520790 rows x 6 columns]

In [125]:
dfCombined_melt_withkeys = pd.DataFrame.merge(dfCombined_melt, dfColKeys, on='col')
dfCombined_melt_withkeys

,SEGID,modVersion,scnGroup,scnYear,col,val,fDir,fVeh,fTod,aCode
0,0006_146.9,v900,Base,2019,LINKS,20,DT,None,None,aLinks
1,0006_149.9,v900,Base,2019,LINKS,2,DT,None,None,aLinks
2,0006_150.6,v900,Base,2019,LINKS,8,DT,None,None,aLinks
3,0006_152.6,v900,Base,2019,LINKS,2,DT,None,None,aLinks
4,0006_152.9,v900,Base,2019,LINKS,6,DT,None,None,aLinks
...,...,...,...,...,...,...,...,...,...,...
3520785,WFRC_8261,v900,TIP,2028,D2_DY_VC,0.08,D2,None,DY,aVc
3520786,WFRC_8263,v900,TIP,2028,D2_DY_VC,0.27,D2,None,DY,aVc
3520787,WFRC_8264,v900,TIP,2028,D2_DY_VC,0.12,D2,None,DY,aVc
3520788,WFRC_8265,v900,TIP,2028,D2_DY_VC,0.09,D2,None,DY,aVc
3520789,WFRC_8266,v900,TIP,2028,D2_DY_VC,0.23,D2,None,DY,aVc

In [126]:
dfCombined_melt_withkeys_pivot_atts = dfCombined_melt_withkeys.pivot(index=[col for col in dfCombined_melt_withkeys.columns if col not in ['aCode','val','col']], columns='aCode', values="val")
dfCombined_melt_withkeys_pivot_atts.columns.name = None
dfCombined_melt_withkeys_pivot_atts.reset_index(inplace=True)
dfCombined_melt_withkeys_pivot_atts

,SEGID,modVersion,scnGroup,scnYear,fDir,fVeh,fTod,aCap1HL,aFfSpd,aFt,aFtClass,aLanes,aLinks,aSpd,aVc,aVol
0,0006_146.9,v900,Base,2019,D1,NaN,NaN,1065,58.0,2.0,Principal Arterial,1.0,10,NaN,NaN,NaN
1,0006_146.9,v900,Base,2019,D1,NaN,AM,NaN,NaN,NaN,NaN,NaN,NaN,58.0,0.03,NaN
2,0006_146.9,v900,Base,2019,D1,NaN,DY,NaN,NaN,NaN,NaN,NaN,NaN,58.0,0.03,NaN
3,0006_146.9,v900,Base,2019,D1,NaN,EV,NaN,NaN,NaN,NaN,NaN,NaN,58.0,0.01,NaN
4,0006_146.9,v900,Base,2019,D1,NaN,MD,NaN,NaN,NaN,NaN,NaN,NaN,58.0,0.02,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2011875,WFRC_8266,v900,TIP,2028,DT,All,MD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1848.3
2011876,WFRC_8266,v900,TIP,2028,DT,All,PM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1768.0
2011877,WFRC_8266,v900,TIP,2028,DT,HV,DY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,315.9
2011878,WFRC_8266,v900,TIP,2028,DT,LT,DY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.3
2011879,WFRC_8266,v900,TIP,2028,DT,MD,DY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,594.3

In [134]:
import json

# PREPARE JSON FOR EACH SCENARIO
# scenarioDetails
# attributes
#   aCode
#   aName
#   filterGroup
# filterGroups
#   possible filterGroup Options
#   for each filterGroup possibility, the data for that selection

_df0 = dfCombined_melt_withkeys_pivot_atts.copy()

# Loop through scenarios in dfScn
for _, row in dfScn.iterrows():


    _scenarioCode = row['modVersion'] + '__' + row['scnGroup'] + '__' + str(row['scnYear'])
    print(_scenarioCode)

    # format scenario details for json export
    jsonScenarioDetails = row.to_dict()

    #print(row['modVersion'] + row['scnGroup'] + str(row['scnYear']))
    # Filter the main dataframe based on the scenario
    _df0_filtered = _df0[
        (_df0['modVersion'] == row['modVersion']) & 
        (_df0['scnGroup'] == row['scnGroup']) & 
        (_df0['scnYear'] == row['scnYear'])
    ].copy()

    _df = _df0_filtered.copy()

    # add options to _dfFiltersWithOptions
    
    _dfFiltersWithOptions = dfFilters.copy()

    # For each fCode, get the unique values from dfData, and join to dfFilters
    formatted_lists = []
    for fCode in dfFilters['fCode']:
        unique_values = [x for x in _df[fCode].unique() if pd.notna(x)]
        formatted_list = str(list(unique_values))
        formatted_lists.append(formatted_list)

    _dfFiltersWithOptions['fOptions'] = formatted_lists

    # get list of fitler groups (any column that begins with f)
    fCols = [col for col in dfCombined_melt_withkeys.columns if col.startswith('f')]
    _df[fCols] = _df[fCols].fillna('')
    _dfFilters = _df[fCols].drop_duplicates()

    # Convert the values to binary form, so 1 where there is a value and 0 elsewhere
    binary_dfFilters = _dfFilters.applymap(lambda x: 0 if x=='' else 1)

    # Get unique rows of combinations
    unique_combinations = binary_dfFilters.drop_duplicates()

    # Convert the unique combinations to a list of tuples
    lstCombinations = list(unique_combinations.itertuples(index=False, name=None))

    # Define a function to convert to binary
    def is_empty_or_not(value):
        return 0 if value=='' else 1

    _dfFilterACodes = pd.DataFrame()

    # loop through all combinations in list
    for combination in lstCombinations:

        # get list of column names with a 1 for given combination
        _dfFilterColsWithValue1 = [col for idx, col in enumerate(fCols) if combination[idx] == 1]

        # create string of column names
        _strFilterGroup = '_'.join(_dfFilterColsWithValue1)

        #print(_strFilterGroup)
        
        # apply condition to dataframe
        condition = (
            (_df['fDir'].apply(is_empty_or_not) == combination[0]) &
            (_df['fVeh'].apply(is_empty_or_not) == combination[1]) &
            (_df['fTod'].apply(is_empty_or_not) == combination[2])
        )
        _filtered_df = _df[condition].copy()
        _filtered_df.drop(columns=['modVersion','scnGroup','scnYear'], inplace=True)
        #display(_filtered_df)

        # Remove columns where all values are NaN
        _filtered_df_noNA = _filtered_df.dropna(axis=1, how='all')
        #display(_filtered_df_noNA)

        _fColsToDrop = [col for col in _filtered_df_noNA.columns if col.startswith('f') and (_filtered_df_noNA[col] == '').all()]

        # Drop the identified columns - only have fCols with values
        _df2 = _filtered_df_noNA.drop(columns=_fColsToDrop)
        #display(_df2)

        # Get list of columns that begin with "a", create a dataframe the filter group for all possible combinations
        aCols = [col for col in _filtered_df_noNA.columns if col.startswith('a')]
        new_data = pd.DataFrame([{"filterGroup": _strFilterGroup, 'aCode': aCols}])
        new_data = new_data.explode('aCode').reset_index(drop=True)
        _dfFilterACodes = pd.concat([_dfFilterACodes, new_data], ignore_index=True)


        # get unique filter values
        _fColsRemain = [col for col in _df2.columns if col.startswith('f')]
        _dfFilterOptions = _df2[_fColsRemain].drop_duplicates()

        first_row = True

        jsonDataCombined = {}

        for index, row in _dfFilterOptions.iterrows():
            # Display or print the filter selection
            #print('"filterSelection": ' + row.to_json())

            # Dynamically construct the filter condition
            shared_columns = set(_dfFilterOptions.columns) & set(_df2.columns)
            conditions = (_df2[col].isin([row[col]]) for col in shared_columns)
            final_condition = next(conditions)

            for condition in conditions:
                final_condition &= condition

            filtered_df2 = _df2[final_condition].copy()
            filtered_df2.drop(columns=_fColsRemain, inplace=True)
            filtered_df2.set_index('SEGID',inplace=True)
            #display(filtered_df2.shape[0])
            jsonFilterSelectionData = filtered_df2.to_json(orient='index')

            # Construct final JSON structure
            jsonData = {
                '_'.join(row.astype(str).values) : json.loads(jsonFilterSelectionData)
            }

            # Append the JSON structure from this iteration to the combined
            jsonDataCombined = {**jsonDataCombined, **jsonData}


    _dfAttributesWFilter = pd.DataFrame.merge(dfAttributes, _dfFilterACodes, on='aCode')
    jsonAttributes = _dfAttributesWFilter.to_dict(orient='records')
    jsonFilters = _dfFiltersWithOptions.to_dict(orient='records')

    # Construct final JSON structure
    jsonScenario = {
        'scenarioDetails': jsonScenarioDetails,
        'attributes': jsonAttributes,
        'filters': jsonFilters,
        'data': jsonDataCombined#,
        #'aggregations': aggregations_list
    }

    # Specify the desired file name
    filename = '_site/data/scnData/' + _scenarioCode + '/roadway-seg-summary.json'

    # Open the file in write mode
    with open(filename, 'w') as file:
        json.dump(jsonScenario, file)

v900__Base__2019
v900__Base__2023
v900__TIP__2028
v900__RTP__2032
v900__RTP__2042
v900__RTP__2050
v900__NoBuild__2032
v900__NoBuild__2042
v900__NoBuild__2050
v900__Needs__2032
v900__Needs__2042
v900__Needs__2050
v900__Needs__2042
v900__Needs MAG__2050

In [131]:
formatted_lists

["['D1', 'D2', 'DT']",
 "[nan, 'AM', 'DY', 'EV', 'MD', 'PM']",
 "[nan, 'All', 'HV', 'LT', 'MD']"]

In [129]:
print(_test)
print(_test)

hi
hi